ghost:
    image: ghost
    volumes:
        - ./blog:/var/lib/ghost

nginx:
    image: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - ghost:ghost